changed composer installation
compare hash with installer.sig instead of a predefined string

diff --git a/hgb-phpdev-base/Vagrantfile b/hgb-phpdev-base/Vagrantfile
--- a/hgb-phpdev-base/Vagrantfile
+++ b/hgb-phpdev-base/Vagrantfile
@@ -91,8 +91,15 @@ Vagrant.configure("2") do |config|
   config.vm.provision "## Installing composer ##", type: "shell",
     inline:  <<-SH
 	  cd /home/vagrant
+      EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
       php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
-      php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
+      ACTUAL_SIGNATURE="$(php -r "echo hash_file('SHA384', 'composer-setup.php');")"
+      if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
+      then
+          >&2 echo '## ERROR: Invalid installer signature for composer. Composer not installed!! ##'
+          rm composer-setup.php
+          exit 1
+      fi
       php composer-setup.php --install-dir=/usr/local/bin
       php -r "unlink('composer-setup.php');"
 	  mv /usr/local/bin/composer.phar /usr/local/bin/composer
@@ -107,7 +114,7 @@ Vagrant.configure("2") do |config|
 	  chown vagrant:vagrant "$MOUNT";
     SH
   
-  config.vm.provision "## Starting Apache and MariaDB always ##", type: "shell", run: "always",
+  config.vm.provision "## Starting Apache and MariaDB with run: always ##", type: "shell", run: "always",
     inline: <<-SH
 	  service apache2 restart   
       service mysql restart
